language: node_js
node_js:
  - 4
notifications:
  email:
    on_success: change
    on_failure: always
before_script:
  - npm link
after_script:
  - npm install coveralls
  - 'npm run coverage | coveralls'
